version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building the React app"
      - npm run build

  post_build:
    commands:
      - echo "Making deploy script executable"
      - sudo chmod +x spricts/deploy.sh
      - echo "Build completed"

artifacts:
  files:
    - appspec.yml
    - spricts/**/*
    - dist/**/*
  discard-paths: no
