version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Build completed"
      - chmod +x scripts/*.sh

artifacts:
  files:
    - appspec.yml
    - package.json
    - package-lock.json
    - index.html
    - vite.config.*
    - src/**/* # <-- This is critical
    - public/**/* # <-- Include if you use public assets
    - scripts/*

  discard-paths: no
